// Service worker for the installable PDF Editor (generated into app/sw.js by
// tools/build-offline.mjs, which fills in VERSION and FILES).
//
// On install it stores every file the app needs, so after the first visit the
// app opens and works with no internet connection. A new build has a new
// VERSION, which makes the browser fetch the new files and drop the old ones.

const VERSION = '98a84e46ea50';
const FILES = [
  "./",
  "app.js",
  "convert.js",
  "editable.js",
  "icons/apple-touch-icon.png",
  "icons/favicon-32.png",
  "icons/icon-192.png",
  "icons/icon-512.png",
  "icons/icon-maskable-512.png",
  "index.html",
  "install.js",
  "manifest.webmanifest",
  "styles.css",
  "vendor/@neslinesli93/qpdf-wasm@0.3.0/dist/qpdf.js",
  "vendor/@neslinesli93/qpdf-wasm@0.3.0/dist/qpdf.wasm",
  "vendor/@tesseract.js-data/eng@1.0.0/4.0.0_best_int/eng.traineddata.gz",
  "vendor/docx-preview@0.4.0/dist/docx-preview.min.js",
  "vendor/heic-to@1.5.2/dist/iife/heic-to.js",
  "vendor/html2canvas@1.4.1/dist/html2canvas.min.js",
  "vendor/jszip@3.10.1/dist/jszip.min.js",
  "vendor/pdf-lib@1.17.1/dist/pdf-lib.min.js",
  "vendor/pdfjs-dist@4.10.38/build/pdf.min.mjs",
  "vendor/pdfjs-dist@4.10.38/build/pdf.worker.min.mjs",
  "vendor/pdfjs-dist@4.10.38/cmaps/78-EUC-H.bcmap",
  "vendor/pdfjs-dist@4.10.38/cmaps/78-EUC-V.bcmap",
  "vendor/pdfjs-dist@4.10.38/cmaps/78-H.bcmap",
  "vendor/pdfjs-dist@4.10.38/cmaps/78-RKSJ-H.bcmap",
  "vendor/pdfjs-dist@4.10.38/cmaps/78-RKSJ-V.bcmap",
  "vendor/pdfjs-dist@4.10.38/cmaps/78-V.bcmap",
  "vendor/pdfjs-dist@4.10.38/cmaps/78ms-RKSJ-H.bcmap",
  "vendor/pdfjs-dist@4.10.38/cmaps/78ms-RKSJ-V.bcmap",
  "vendor/pdfjs-dist@4.10.38/cmaps/83pv-RKSJ-H.bcmap",
  "vendor/pdfjs-dist@4.10.38/cmaps/90ms-RKSJ-H.bcmap",
  "vendor/pdfjs-dist@4.10.38/cmaps/90ms-RKSJ-V.bcmap",
  "vendor/pdfjs-dist@4.10.38/cmaps/90msp-RKSJ-H.bcmap",
  "vendor/pdfjs-dist@4.10.38/cmaps/90msp-RKSJ-V.bcmap",
  "vendor/pdfjs-dist@4.10.38/cmaps/90pv-RKSJ-H.bcmap",
  "vendor/pdfjs-dist@4.10.38/cmaps/90pv-RKSJ-V.bcmap",
  "vendor/pdfjs-dist@4.10.38/cmaps/Add-H.bcmap",
  "vendor/pdfjs-dist@4.10.38/cmaps/Add-RKSJ-H.bcmap",
  "vendor/pdfjs-dist@4.10.38/cmaps/Add-RKSJ-V.bcmap",
  "vendor/pdfjs-dist@4.10.38/cmaps/Add-V.bcmap",
  "vendor/pdfjs-dist@4.10.38/cmaps/Adobe-CNS1-0.bcmap",
  "vendor/pdfjs-dist@4.10.38/cmaps/Adobe-CNS1-1.bcmap",
  "vendor/pdfjs-dist@4.10.38/cmaps/Adobe-CNS1-2.bcmap",
  "vendor/pdfjs-dist@4.10.38/cmaps/Adobe-CNS1-3.bcmap",
  "vendor/pdfjs-dist@4.10.38/cmaps/Adobe-CNS1-4.bcmap",
  "vendor/pdfjs-dist@4.10.38/cmaps/Adobe-CNS1-5.bcmap",
  "vendor/pdfjs-dist@4.10.38/cmaps/Adobe-CNS1-6.bcmap",
  "vendor/pdfjs-dist@4.10.38/cmaps/Adobe-CNS1-UCS2.bcmap",
  "vendor/pdfjs-dist@4.10.38/cmaps/Adobe-GB1-0.bcmap",
  "vendor/pdfjs-dist@4.10.38/cmaps/Adobe-GB1-1.bcmap",
  "vendor/pdfjs-dist@4.10.38/cmaps/Adobe-GB1-2.bcmap",
  "vendor/pdfjs-dist@4.10.38/cmaps/Adobe-GB1-3.bcmap",
  "vendor/pdfjs-dist@4.10.38/cmaps/Adobe-GB1-4.bcmap",
  "vendor/pdfjs-dist@4.10.38/cmaps/Adobe-GB1-5.bcmap",
  "vendor/pdfjs-dist@4.10.38/cmaps/Adobe-GB1-UCS2.bcmap",
  "vendor/pdfjs-dist@4.10.38/cmaps/Adobe-Japan1-0.bcmap",
  "vendor/pdfjs-dist@4.10.38/cmaps/Adobe-Japan1-1.bcmap",
  "vendor/pdfjs-dist@4.10.38/cmaps/Adobe-Japan1-2.bcmap",
  "vendor/pdfjs-dist@4.10.38/cmaps/Adobe-Japan1-3.bcmap",
  "vendor/pdfjs-dist@4.10.38/cmaps/Adobe-Japan1-4.bcmap",
  "vendor/pdfjs-dist@4.10.38/cmaps/Adobe-Japan1-5.bcmap",
  "vendor/pdfjs-dist@4.10.38/cmaps/Adobe-Japan1-6.bcmap",
  "vendor/pdfjs-dist@4.10.38/cmaps/Adobe-Japan1-UCS2.bcmap",
  "vendor/pdfjs-dist@4.10.38/cmaps/Adobe-Korea1-0.bcmap",
  "vendor/pdfjs-dist@4.10.38/cmaps/Adobe-Korea1-1.bcmap",
  "vendor/pdfjs-dist@4.10.38/cmaps/Adobe-Korea1-2.bcmap",
  "vendor/pdfjs-dist@4.10.38/cmaps/Adobe-Korea1-UCS2.bcmap",
  "vendor/pdfjs-dist@4.10.38/cmaps/B5-H.bcmap",
  "vendor/pdfjs-dist@4.10.38/cmaps/B5-V.bcmap",
  "vendor/pdfjs-dist@4.10.38/cmaps/B5pc-H.bcmap",
  "vendor/pdfjs-dist@4.10.38/cmaps/B5pc-V.bcmap",
  "vendor/pdfjs-dist@4.10.38/cmaps/CNS-EUC-H.bcmap",
  "vendor/pdfjs-dist@4.10.38/cmaps/CNS-EUC-V.bcmap",
  "vendor/pdfjs-dist@4.10.38/cmaps/CNS1-H.bcmap",
  "vendor/pdfjs-dist@4.10.38/cmaps/CNS1-V.bcmap",
  "vendor/pdfjs-dist@4.10.38/cmaps/CNS2-H.bcmap",
  "vendor/pdfjs-dist@4.10.38/cmaps/CNS2-V.bcmap",
  "vendor/pdfjs-dist@4.10.38/cmaps/ETHK-B5-H.bcmap",
  "vendor/pdfjs-dist@4.10.38/cmaps/ETHK-B5-V.bcmap",
  "vendor/pdfjs-dist@4.10.38/cmaps/ETen-B5-H.bcmap",
  "vendor/pdfjs-dist@4.10.38/cmaps/ETen-B5-V.bcmap",
  "vendor/pdfjs-dist@4.10.38/cmaps/ETenms-B5-H.bcmap",
  "vendor/pdfjs-dist@4.10.38/cmaps/ETenms-B5-V.bcmap",
  "vendor/pdfjs-dist@4.10.38/cmaps/EUC-H.bcmap",
  "vendor/pdfjs-dist@4.10.38/cmaps/EUC-V.bcmap",
  "vendor/pdfjs-dist@4.10.38/cmaps/Ext-H.bcmap",
  "vendor/pdfjs-dist@4.10.38/cmaps/Ext-RKSJ-H.bcmap",
  "vendor/pdfjs-dist@4.10.38/cmaps/Ext-RKSJ-V.bcmap",
  "vendor/pdfjs-dist@4.10.38/cmaps/Ext-V.bcmap",
  "vendor/pdfjs-dist@4.10.38/cmaps/GB-EUC-H.bcmap",
  "vendor/pdfjs-dist@4.10.38/cmaps/GB-EUC-V.bcmap",
  "vendor/pdfjs-dist@4.10.38/cmaps/GB-H.bcmap",
  "vendor/pdfjs-dist@4.10.38/cmaps/GB-V.bcmap",
  "vendor/pdfjs-dist@4.10.38/cmaps/GBK-EUC-H.bcmap",
  "vendor/pdfjs-dist@4.10.38/cmaps/GBK-EUC-V.bcmap",
  "vendor/pdfjs-dist@4.10.38/cmaps/GBK2K-H.bcmap",
  "vendor/pdfjs-dist@4.10.38/cmaps/GBK2K-V.bcmap",
  "vendor/pdfjs-dist@4.10.38/cmaps/GBKp-EUC-H.bcmap",
  "vendor/pdfjs-dist@4.10.38/cmaps/GBKp-EUC-V.bcmap",
  "vendor/pdfjs-dist@4.10.38/cmaps/GBT-EUC-H.bcmap",
  "vendor/pdfjs-dist@4.10.38/cmaps/GBT-EUC-V.bcmap",
  "vendor/pdfjs-dist@4.10.38/cmaps/GBT-H.bcmap",
  "vendor/pdfjs-dist@4.10.38/cmaps/GBT-V.bcmap",
  "vendor/pdfjs-dist@4.10.38/cmaps/GBTpc-EUC-H.bcmap",
  "vendor/pdfjs-dist@4.10.38/cmaps/GBTpc-EUC-V.bcmap",
  "vendor/pdfjs-dist@4.10.38/cmaps/GBpc-EUC-H.bcmap",
  "vendor/pdfjs-dist@4.10.38/cmaps/GBpc-EUC-V.bcmap",
  "vendor/pdfjs-dist@4.10.38/cmaps/H.bcmap",
  "vendor/pdfjs-dist@4.10.38/cmaps/HKdla-B5-H.bcmap",
  "vendor/pdfjs-dist@4.10.38/cmaps/HKdla-B5-V.bcmap",
  "vendor/pdfjs-dist@4.10.38/cmaps/HKdlb-B5-H.bcmap",
  "vendor/pdfjs-dist@4.10.38/cmaps/HKdlb-B5-V.bcmap",
  "vendor/pdfjs-dist@4.10.38/cmaps/HKgccs-B5-H.bcmap",
  "vendor/pdfjs-dist@4.10.38/cmaps/HKgccs-B5-V.bcmap",
  "vendor/pdfjs-dist@4.10.38/cmaps/HKm314-B5-H.bcmap",
  "vendor/pdfjs-dist@4.10.38/cmaps/HKm314-B5-V.bcmap",
  "vendor/pdfjs-dist@4.10.38/cmaps/HKm471-B5-H.bcmap",
  "vendor/pdfjs-dist@4.10.38/cmaps/HKm471-B5-V.bcmap",
  "vendor/pdfjs-dist@4.10.38/cmaps/HKscs-B5-H.bcmap",
  "vendor/pdfjs-dist@4.10.38/cmaps/HKscs-B5-V.bcmap",
  "vendor/pdfjs-dist@4.10.38/cmaps/Hankaku.bcmap",
  "vendor/pdfjs-dist@4.10.38/cmaps/Hiragana.bcmap",
  "vendor/pdfjs-dist@4.10.38/cmaps/KSC-EUC-H.bcmap",
  "vendor/pdfjs-dist@4.10.38/cmaps/KSC-EUC-V.bcmap",
  "vendor/pdfjs-dist@4.10.38/cmaps/KSC-H.bcmap",
  "vendor/pdfjs-dist@4.10.38/cmaps/KSC-Johab-H.bcmap",
  "vendor/pdfjs-dist@4.10.38/cmaps/KSC-Johab-V.bcmap",
  "vendor/pdfjs-dist@4.10.38/cmaps/KSC-V.bcmap",
  "vendor/pdfjs-dist@4.10.38/cmaps/KSCms-UHC-H.bcmap",
  "vendor/pdfjs-dist@4.10.38/cmaps/KSCms-UHC-HW-H.bcmap",
  "vendor/pdfjs-dist@4.10.38/cmaps/KSCms-UHC-HW-V.bcmap",
  "vendor/pdfjs-dist@4.10.38/cmaps/KSCms-UHC-V.bcmap",
  "vendor/pdfjs-dist@4.10.38/cmaps/KSCpc-EUC-H.bcmap",
  "vendor/pdfjs-dist@4.10.38/cmaps/KSCpc-EUC-V.bcmap",
  "vendor/pdfjs-dist@4.10.38/cmaps/Katakana.bcmap",
  "vendor/pdfjs-dist@4.10.38/cmaps/LICENSE",
  "vendor/pdfjs-dist@4.10.38/cmaps/NWP-H.bcmap",
  "vendor/pdfjs-dist@4.10.38/cmaps/NWP-V.bcmap",
  "vendor/pdfjs-dist@4.10.38/cmaps/RKSJ-H.bcmap",
  "vendor/pdfjs-dist@4.10.38/cmaps/RKSJ-V.bcmap",
  "vendor/pdfjs-dist@4.10.38/cmaps/Roman.bcmap",
  "vendor/pdfjs-dist@4.10.38/cmaps/UniCNS-UCS2-H.bcmap",
  "vendor/pdfjs-dist@4.10.38/cmaps/UniCNS-UCS2-V.bcmap",
  "vendor/pdfjs-dist@4.10.38/cmaps/UniCNS-UTF16-H.bcmap",
  "vendor/pdfjs-dist@4.10.38/cmaps/UniCNS-UTF16-V.bcmap",
  "vendor/pdfjs-dist@4.10.38/cmaps/UniCNS-UTF32-H.bcmap",
  "vendor/pdfjs-dist@4.10.38/cmaps/UniCNS-UTF32-V.bcmap",
  "vendor/pdfjs-dist@4.10.38/cmaps/UniCNS-UTF8-H.bcmap",
  "vendor/pdfjs-dist@4.10.38/cmaps/UniCNS-UTF8-V.bcmap",
  "vendor/pdfjs-dist@4.10.38/cmaps/UniGB-UCS2-H.bcmap",
  "vendor/pdfjs-dist@4.10.38/cmaps/UniGB-UCS2-V.bcmap",
  "vendor/pdfjs-dist@4.10.38/cmaps/UniGB-UTF16-H.bcmap",
  "vendor/pdfjs-dist@4.10.38/cmaps/UniGB-UTF16-V.bcmap",
  "vendor/pdfjs-dist@4.10.38/cmaps/UniGB-UTF32-H.bcmap",
  "vendor/pdfjs-dist@4.10.38/cmaps/UniGB-UTF32-V.bcmap",
  "vendor/pdfjs-dist@4.10.38/cmaps/UniGB-UTF8-H.bcmap",
  "vendor/pdfjs-dist@4.10.38/cmaps/UniGB-UTF8-V.bcmap",
  "vendor/pdfjs-dist@4.10.38/cmaps/UniJIS-UCS2-H.bcmap",
  "vendor/pdfjs-dist@4.10.38/cmaps/UniJIS-UCS2-HW-H.bcmap",
  "vendor/pdfjs-dist@4.10.38/cmaps/UniJIS-UCS2-HW-V.bcmap",
  "vendor/pdfjs-dist@4.10.38/cmaps/UniJIS-UCS2-V.bcmap",
  "vendor/pdfjs-dist@4.10.38/cmaps/UniJIS-UTF16-H.bcmap",
  "vendor/pdfjs-dist@4.10.38/cmaps/UniJIS-UTF16-V.bcmap",
  "vendor/pdfjs-dist@4.10.38/cmaps/UniJIS-UTF32-H.bcmap",
  "vendor/pdfjs-dist@4.10.38/cmaps/UniJIS-UTF32-V.bcmap",
  "vendor/pdfjs-dist@4.10.38/cmaps/UniJIS-UTF8-H.bcmap",
  "vendor/pdfjs-dist@4.10.38/cmaps/UniJIS-UTF8-V.bcmap",
  "vendor/pdfjs-dist@4.10.38/cmaps/UniJIS2004-UTF16-H.bcmap",
  "vendor/pdfjs-dist@4.10.38/cmaps/UniJIS2004-UTF16-V.bcmap",
  "vendor/pdfjs-dist@4.10.38/cmaps/UniJIS2004-UTF32-H.bcmap",
  "vendor/pdfjs-dist@4.10.38/cmaps/UniJIS2004-UTF32-V.bcmap",
  "vendor/pdfjs-dist@4.10.38/cmaps/UniJIS2004-UTF8-H.bcmap",
  "vendor/pdfjs-dist@4.10.38/cmaps/UniJIS2004-UTF8-V.bcmap",
  "vendor/pdfjs-dist@4.10.38/cmaps/UniJISPro-UCS2-HW-V.bcmap",
  "vendor/pdfjs-dist@4.10.38/cmaps/UniJISPro-UCS2-V.bcmap",
  "vendor/pdfjs-dist@4.10.38/cmaps/UniJISPro-UTF8-V.bcmap",
  "vendor/pdfjs-dist@4.10.38/cmaps/UniJISX0213-UTF32-H.bcmap",
  "vendor/pdfjs-dist@4.10.38/cmaps/UniJISX0213-UTF32-V.bcmap",
  "vendor/pdfjs-dist@4.10.38/cmaps/UniJISX02132004-UTF32-H.bcmap",
  "vendor/pdfjs-dist@4.10.38/cmaps/UniJISX02132004-UTF32-V.bcmap",
  "vendor/pdfjs-dist@4.10.38/cmaps/UniKS-UCS2-H.bcmap",
  "vendor/pdfjs-dist@4.10.38/cmaps/UniKS-UCS2-V.bcmap",
  "vendor/pdfjs-dist@4.10.38/cmaps/UniKS-UTF16-H.bcmap",
  "vendor/pdfjs-dist@4.10.38/cmaps/UniKS-UTF16-V.bcmap",
  "vendor/pdfjs-dist@4.10.38/cmaps/UniKS-UTF32-H.bcmap",
  "vendor/pdfjs-dist@4.10.38/cmaps/UniKS-UTF32-V.bcmap",
  "vendor/pdfjs-dist@4.10.38/cmaps/UniKS-UTF8-H.bcmap",
  "vendor/pdfjs-dist@4.10.38/cmaps/UniKS-UTF8-V.bcmap",
  "vendor/pdfjs-dist@4.10.38/cmaps/V.bcmap",
  "vendor/pdfjs-dist@4.10.38/cmaps/WP-Symbol.bcmap",
  "vendor/pdfjs-dist@4.10.38/standard_fonts/FoxitDingbats.pfb",
  "vendor/pdfjs-dist@4.10.38/standard_fonts/FoxitFixed.pfb",
  "vendor/pdfjs-dist@4.10.38/standard_fonts/FoxitFixedBold.pfb",
  "vendor/pdfjs-dist@4.10.38/standard_fonts/FoxitFixedBoldItalic.pfb",
  "vendor/pdfjs-dist@4.10.38/standard_fonts/FoxitFixedItalic.pfb",
  "vendor/pdfjs-dist@4.10.38/standard_fonts/FoxitSerif.pfb",
  "vendor/pdfjs-dist@4.10.38/standard_fonts/FoxitSerifBold.pfb",
  "vendor/pdfjs-dist@4.10.38/standard_fonts/FoxitSerifBoldItalic.pfb",
  "vendor/pdfjs-dist@4.10.38/standard_fonts/FoxitSerifItalic.pfb",
  "vendor/pdfjs-dist@4.10.38/standard_fonts/FoxitSymbol.pfb",
  "vendor/pdfjs-dist@4.10.38/standard_fonts/LICENSE_FOXIT",
  "vendor/pdfjs-dist@4.10.38/standard_fonts/LICENSE_LIBERATION",
  "vendor/pdfjs-dist@4.10.38/standard_fonts/LiberationSans-Bold.ttf",
  "vendor/pdfjs-dist@4.10.38/standard_fonts/LiberationSans-BoldItalic.ttf",
  "vendor/pdfjs-dist@4.10.38/standard_fonts/LiberationSans-Italic.ttf",
  "vendor/pdfjs-dist@4.10.38/standard_fonts/LiberationSans-Regular.ttf",
  "vendor/tesseract.js-core@5.1.1/tesseract-core-lstm.wasm.js",
  "vendor/tesseract.js-core@5.1.1/tesseract-core-simd-lstm.wasm.js",
  "vendor/tesseract.js@5.1.1/dist/tesseract.min.js",
  "vendor/tesseract.js@5.1.1/dist/worker.min.js"
];
const CACHE = `pdf-editor-${VERSION}`;

self.addEventListener('install', (event) => {
  event.waitUntil((async () => {
    const cache = await caches.open(CACHE);
    // "reload" skips the browser's HTTP cache, so a new version never mixes in old files.
    await cache.addAll(FILES.map((f) => new Request(f, { cache: 'reload' })));
    await self.skipWaiting();
  })());
});

self.addEventListener('activate', (event) => {
  event.waitUntil((async () => {
    for (const key of await caches.keys()) {
      if (key.startsWith('pdf-editor-') && key !== CACHE) await caches.delete(key);
    }
    await self.clients.claim();
  })());
});

self.addEventListener('fetch', (event) => {
  const req = event.request;
  if (req.method !== 'GET' || new URL(req.url).origin !== self.location.origin) return;
  event.respondWith((async () => {
    const cache = await caches.open(CACHE);
    const hit = (await cache.match(req, { ignoreSearch: true })) ||
      (req.mode === 'navigate' ? await cache.match('./') : undefined);
    return hit || fetch(req);
  })());
});
